/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as WidgetAgentIdRouteImport } from './routes/widget.$agentId'
import { Route as DashboardPhoneNumbersRouteImport } from './routes/dashboard.phone-numbers'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard.onboarding'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardKnowledgeRouteImport } from './routes/dashboard.knowledge'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard.conversations'
import { Route as DashboardChatWidgetRouteImport } from './routes/dashboard.chat-widget'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAgentRouteImport } from './routes/dashboard.agent'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardConversationsIndexRouteImport } from './routes/dashboard.conversations.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardConversationsBlockedRouteImport } from './routes/dashboard.conversations.blocked'
import { Route as DashboardConversationsConversationIdRouteImport } from './routes/dashboard.conversations.$conversationId'
import { Route as DashboardAgentsAgentIdRouteImport } from './routes/dashboard.agents.$agentId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminTicketsRouteImport } from './routes/dashboard.admin.tickets'
import { Route as DashboardAdminHealthRouteImport } from './routes/dashboard.admin.health'
import { Route as ApiPublicOwnerChatRouteImport } from './routes/api.public.owner-chat'
import { Route as DashboardAdminUsersIndexRouteImport } from './routes/dashboard.admin.users.index'
import { Route as DashboardAdminTicketsIndexRouteImport } from './routes/dashboard.admin.tickets.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as DashboardAdminUsersUserIdRouteImport } from './routes/dashboard.admin.users.$userId'
import { Route as DashboardAdminTicketsTicketIdRouteImport } from './routes/dashboard.admin.tickets.$ticketId'
import { Route as ApiPublicWidgetEmbedDotjsRouteImport } from './routes/api.public.widget.embed[.]js'
import { Route as ApiPublicWidgetChatRouteImport } from './routes/api.public.widget.chat'
import { Route as ApiPublicVoicemailAudioRouteImport } from './routes/api.public.voicemail.audio'
import { Route as ApiPublicVoiceToolsFindSlotsRouteImport } from './routes/api.public.voice-tools.find-slots'
import { Route as ApiPublicVoiceToolsBookAppointmentRouteImport } from './routes/api.public.voice-tools.book-appointment'
import { Route as ApiPublicTwilioVoiceFallbackRouteImport } from './routes/api.public.twilio.voice-fallback'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api.public.twilio.voice'
import { Route as ApiPublicTwilioSmsRouteImport } from './routes/api.public.twilio.sms'
import { Route as ApiPublicTwilioDialerBridgeRouteImport } from './routes/api.public.twilio.dialer-bridge'
import { Route as ApiPublicTwilioCallbackRouteImport } from './routes/api.public.twilio.callback'
import { Route as ApiPublicOutlookCalendarCallbackRouteImport } from './routes/api.public.outlook-calendar.callback'
import { Route as ApiPublicHooksAutoDeleteThreadsRouteImport } from './routes/api.public.hooks.auto-delete-threads'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api.public.google-calendar.callback'
import { Route as ApiPublicElevenlabsPostcallRouteImport } from './routes/api.public.elevenlabs.postcall'
import { Route as ApiPublicWidgetConfigAgentIdRouteImport } from './routes/api.public.widget.config.$agentId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const WidgetAgentIdRoute = WidgetAgentIdRouteImport.update({
  id: '/widget/$agentId',
  path: '/widget/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPhoneNumbersRoute = DashboardPhoneNumbersRouteImport.update({
  id: '/phone-numbers',
  path: '/phone-numbers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeRoute = DashboardKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatWidgetRoute = DashboardChatWidgetRouteImport.update({
  id: '/chat-widget',
  path: '/chat-widget',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentRoute = DashboardAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsIndexRoute =
  DashboardConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardConversationsRoute,
  } as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardConversationsBlockedRoute =
  DashboardConversationsBlockedRouteImport.update({
    id: '/blocked',
    path: '/blocked',
    getParentRoute: () => DashboardConversationsRoute,
  } as any)
const DashboardConversationsConversationIdRoute =
  DashboardConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => DashboardConversationsRoute,
  } as any)
const DashboardAgentsAgentIdRoute = DashboardAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTicketsRoute = DashboardAdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminHealthRoute = DashboardAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ApiPublicOwnerChatRoute = ApiPublicOwnerChatRouteImport.update({
  id: '/api/public/owner-chat',
  path: '/api/public/owner-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminUsersIndexRoute =
  DashboardAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdminUsersRoute,
  } as any)
const DashboardAdminTicketsIndexRoute =
  DashboardAdminTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdminTicketsRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminUsersUserIdRoute =
  DashboardAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => DashboardAdminUsersRoute,
  } as any)
const DashboardAdminTicketsTicketIdRoute =
  DashboardAdminTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => DashboardAdminTicketsRoute,
  } as any)
const ApiPublicWidgetEmbedDotjsRoute =
  ApiPublicWidgetEmbedDotjsRouteImport.update({
    id: '/api/public/widget/embed.js',
    path: '/api/public/widget/embed.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetChatRoute = ApiPublicWidgetChatRouteImport.update({
  id: '/api/public/widget/chat',
  path: '/api/public/widget/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoicemailAudioRoute = ApiPublicVoicemailAudioRouteImport.update({
  id: '/api/public/voicemail/audio',
  path: '/api/public/voicemail/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceToolsFindSlotsRoute =
  ApiPublicVoiceToolsFindSlotsRouteImport.update({
    id: '/api/public/voice-tools/find-slots',
    path: '/api/public/voice-tools/find-slots',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVoiceToolsBookAppointmentRoute =
  ApiPublicVoiceToolsBookAppointmentRouteImport.update({
    id: '/api/public/voice-tools/book-appointment',
    path: '/api/public/voice-tools/book-appointment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceFallbackRoute =
  ApiPublicTwilioVoiceFallbackRouteImport.update({
    id: '/api/public/twilio/voice-fallback',
    path: '/api/public/twilio/voice-fallback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsRoute = ApiPublicTwilioSmsRouteImport.update({
  id: '/api/public/twilio/sms',
  path: '/api/public/twilio/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioDialerBridgeRoute =
  ApiPublicTwilioDialerBridgeRouteImport.update({
    id: '/api/public/twilio/dialer-bridge',
    path: '/api/public/twilio/dialer-bridge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioCallbackRoute = ApiPublicTwilioCallbackRouteImport.update({
  id: '/api/public/twilio/callback',
  path: '/api/public/twilio/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutlookCalendarCallbackRoute =
  ApiPublicOutlookCalendarCallbackRouteImport.update({
    id: '/api/public/outlook-calendar/callback',
    path: '/api/public/outlook-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoDeleteThreadsRoute =
  ApiPublicHooksAutoDeleteThreadsRouteImport.update({
    id: '/api/public/hooks/auto-delete-threads',
    path: '/api/public/hooks/auto-delete-threads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google-calendar/callback',
    path: '/api/public/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsPostcallRoute =
  ApiPublicElevenlabsPostcallRouteImport.update({
    id: '/api/public/elevenlabs/postcall',
    path: '/api/public/elevenlabs/postcall',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetConfigAgentIdRoute =
  ApiPublicWidgetConfigAgentIdRouteImport.update({
    id: '/api/public/widget/config/$agentId',
    path: '/api/public/widget/config/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/chat-widget': typeof DashboardChatWidgetRoute
  '/dashboard/conversations': typeof DashboardConversationsRouteWithChildren
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/phone-numbers': typeof DashboardPhoneNumbersRoute
  '/widget/$agentId': typeof WidgetAgentIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/owner-chat': typeof ApiPublicOwnerChatRoute
  '/dashboard/admin/health': typeof DashboardAdminHealthRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRouteWithChildren
  '/dashboard/admin/users': typeof DashboardAdminUsersRouteWithChildren
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRoute
  '/dashboard/conversations/$conversationId': typeof DashboardConversationsConversationIdRoute
  '/dashboard/conversations/blocked': typeof DashboardConversationsBlockedRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/conversations/': typeof DashboardConversationsIndexRoute
  '/api/public/elevenlabs/postcall': typeof ApiPublicElevenlabsPostcallRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/hooks/auto-delete-threads': typeof ApiPublicHooksAutoDeleteThreadsRoute
  '/api/public/outlook-calendar/callback': typeof ApiPublicOutlookCalendarCallbackRoute
  '/api/public/twilio/callback': typeof ApiPublicTwilioCallbackRoute
  '/api/public/twilio/dialer-bridge': typeof ApiPublicTwilioDialerBridgeRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/public/twilio/voice-fallback': typeof ApiPublicTwilioVoiceFallbackRoute
  '/api/public/voice-tools/book-appointment': typeof ApiPublicVoiceToolsBookAppointmentRoute
  '/api/public/voice-tools/find-slots': typeof ApiPublicVoiceToolsFindSlotsRoute
  '/api/public/voicemail/audio': typeof ApiPublicVoicemailAudioRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/dashboard/admin/tickets/$ticketId': typeof DashboardAdminTicketsTicketIdRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/dashboard/admin/tickets/': typeof DashboardAdminTicketsIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/api/public/widget/config/$agentId': typeof ApiPublicWidgetConfigAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/chat-widget': typeof DashboardChatWidgetRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/phone-numbers': typeof DashboardPhoneNumbersRoute
  '/widget/$agentId': typeof WidgetAgentIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/owner-chat': typeof ApiPublicOwnerChatRoute
  '/dashboard/admin/health': typeof DashboardAdminHealthRoute
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRoute
  '/dashboard/conversations/$conversationId': typeof DashboardConversationsConversationIdRoute
  '/dashboard/conversations/blocked': typeof DashboardConversationsBlockedRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/conversations': typeof DashboardConversationsIndexRoute
  '/api/public/elevenlabs/postcall': typeof ApiPublicElevenlabsPostcallRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/hooks/auto-delete-threads': typeof ApiPublicHooksAutoDeleteThreadsRoute
  '/api/public/outlook-calendar/callback': typeof ApiPublicOutlookCalendarCallbackRoute
  '/api/public/twilio/callback': typeof ApiPublicTwilioCallbackRoute
  '/api/public/twilio/dialer-bridge': typeof ApiPublicTwilioDialerBridgeRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/public/twilio/voice-fallback': typeof ApiPublicTwilioVoiceFallbackRoute
  '/api/public/voice-tools/book-appointment': typeof ApiPublicVoiceToolsBookAppointmentRoute
  '/api/public/voice-tools/find-slots': typeof ApiPublicVoiceToolsFindSlotsRoute
  '/api/public/voicemail/audio': typeof ApiPublicVoicemailAudioRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/dashboard/admin/tickets/$ticketId': typeof DashboardAdminTicketsTicketIdRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersIndexRoute
  '/api/public/widget/config/$agentId': typeof ApiPublicWidgetConfigAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/agent': typeof DashboardAgentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/chat-widget': typeof DashboardChatWidgetRoute
  '/dashboard/conversations': typeof DashboardConversationsRouteWithChildren
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/phone-numbers': typeof DashboardPhoneNumbersRoute
  '/widget/$agentId': typeof WidgetAgentIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/owner-chat': typeof ApiPublicOwnerChatRoute
  '/dashboard/admin/health': typeof DashboardAdminHealthRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRouteWithChildren
  '/dashboard/admin/users': typeof DashboardAdminUsersRouteWithChildren
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRoute
  '/dashboard/conversations/$conversationId': typeof DashboardConversationsConversationIdRoute
  '/dashboard/conversations/blocked': typeof DashboardConversationsBlockedRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/conversations/': typeof DashboardConversationsIndexRoute
  '/api/public/elevenlabs/postcall': typeof ApiPublicElevenlabsPostcallRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/hooks/auto-delete-threads': typeof ApiPublicHooksAutoDeleteThreadsRoute
  '/api/public/outlook-calendar/callback': typeof ApiPublicOutlookCalendarCallbackRoute
  '/api/public/twilio/callback': typeof ApiPublicTwilioCallbackRoute
  '/api/public/twilio/dialer-bridge': typeof ApiPublicTwilioDialerBridgeRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/api/public/twilio/voice-fallback': typeof ApiPublicTwilioVoiceFallbackRoute
  '/api/public/voice-tools/book-appointment': typeof ApiPublicVoiceToolsBookAppointmentRoute
  '/api/public/voice-tools/find-slots': typeof ApiPublicVoiceToolsFindSlotsRoute
  '/api/public/voicemail/audio': typeof ApiPublicVoicemailAudioRoute
  '/api/public/widget/chat': typeof ApiPublicWidgetChatRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/dashboard/admin/tickets/$ticketId': typeof DashboardAdminTicketsTicketIdRoute
  '/dashboard/admin/users/$userId': typeof DashboardAdminUsersUserIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/dashboard/admin/tickets/': typeof DashboardAdminTicketsIndexRoute
  '/dashboard/admin/users/': typeof DashboardAdminUsersIndexRoute
  '/api/public/widget/config/$agentId': typeof ApiPublicWidgetConfigAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/chat-widget'
    | '/dashboard/conversations'
    | '/dashboard/help'
    | '/dashboard/knowledge'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/onboarding'
    | '/dashboard/phone-numbers'
    | '/widget/$agentId'
    | '/dashboard/'
    | '/api/public/owner-chat'
    | '/dashboard/admin/health'
    | '/dashboard/admin/tickets'
    | '/dashboard/admin/users'
    | '/dashboard/agents/$agentId'
    | '/dashboard/conversations/$conversationId'
    | '/dashboard/conversations/blocked'
    | '/dashboard/admin/'
    | '/dashboard/conversations/'
    | '/api/public/elevenlabs/postcall'
    | '/api/public/google-calendar/callback'
    | '/api/public/hooks/auto-delete-threads'
    | '/api/public/outlook-calendar/callback'
    | '/api/public/twilio/callback'
    | '/api/public/twilio/dialer-bridge'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
    | '/api/public/twilio/voice-fallback'
    | '/api/public/voice-tools/book-appointment'
    | '/api/public/voice-tools/find-slots'
    | '/api/public/voicemail/audio'
    | '/api/public/widget/chat'
    | '/api/public/widget/embed.js'
    | '/dashboard/admin/tickets/$ticketId'
    | '/dashboard/admin/users/$userId'
    | '/lovable/email/queue/process'
    | '/dashboard/admin/tickets/'
    | '/dashboard/admin/users/'
    | '/api/public/widget/config/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/agent'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/chat-widget'
    | '/dashboard/help'
    | '/dashboard/knowledge'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/onboarding'
    | '/dashboard/phone-numbers'
    | '/widget/$agentId'
    | '/dashboard'
    | '/api/public/owner-chat'
    | '/dashboard/admin/health'
    | '/dashboard/agents/$agentId'
    | '/dashboard/conversations/$conversationId'
    | '/dashboard/conversations/blocked'
    | '/dashboard/admin'
    | '/dashboard/conversations'
    | '/api/public/elevenlabs/postcall'
    | '/api/public/google-calendar/callback'
    | '/api/public/hooks/auto-delete-threads'
    | '/api/public/outlook-calendar/callback'
    | '/api/public/twilio/callback'
    | '/api/public/twilio/dialer-bridge'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
    | '/api/public/twilio/voice-fallback'
    | '/api/public/voice-tools/book-appointment'
    | '/api/public/voice-tools/find-slots'
    | '/api/public/voicemail/audio'
    | '/api/public/widget/chat'
    | '/api/public/widget/embed.js'
    | '/dashboard/admin/tickets/$ticketId'
    | '/dashboard/admin/users/$userId'
    | '/lovable/email/queue/process'
    | '/dashboard/admin/tickets'
    | '/dashboard/admin/users'
    | '/api/public/widget/config/$agentId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/analytics'
    | '/dashboard/bookings'
    | '/dashboard/chat-widget'
    | '/dashboard/conversations'
    | '/dashboard/help'
    | '/dashboard/knowledge'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/onboarding'
    | '/dashboard/phone-numbers'
    | '/widget/$agentId'
    | '/dashboard/'
    | '/api/public/owner-chat'
    | '/dashboard/admin/health'
    | '/dashboard/admin/tickets'
    | '/dashboard/admin/users'
    | '/dashboard/agents/$agentId'
    | '/dashboard/conversations/$conversationId'
    | '/dashboard/conversations/blocked'
    | '/dashboard/admin/'
    | '/dashboard/conversations/'
    | '/api/public/elevenlabs/postcall'
    | '/api/public/google-calendar/callback'
    | '/api/public/hooks/auto-delete-threads'
    | '/api/public/outlook-calendar/callback'
    | '/api/public/twilio/callback'
    | '/api/public/twilio/dialer-bridge'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
    | '/api/public/twilio/voice-fallback'
    | '/api/public/voice-tools/book-appointment'
    | '/api/public/voice-tools/find-slots'
    | '/api/public/voicemail/audio'
    | '/api/public/widget/chat'
    | '/api/public/widget/embed.js'
    | '/dashboard/admin/tickets/$ticketId'
    | '/dashboard/admin/users/$userId'
    | '/lovable/email/queue/process'
    | '/dashboard/admin/tickets/'
    | '/dashboard/admin/users/'
    | '/api/public/widget/config/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WidgetAgentIdRoute: typeof WidgetAgentIdRoute
  ApiPublicOwnerChatRoute: typeof ApiPublicOwnerChatRoute
  ApiPublicElevenlabsPostcallRoute: typeof ApiPublicElevenlabsPostcallRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
  ApiPublicHooksAutoDeleteThreadsRoute: typeof ApiPublicHooksAutoDeleteThreadsRoute
  ApiPublicOutlookCalendarCallbackRoute: typeof ApiPublicOutlookCalendarCallbackRoute
  ApiPublicTwilioCallbackRoute: typeof ApiPublicTwilioCallbackRoute
  ApiPublicTwilioDialerBridgeRoute: typeof ApiPublicTwilioDialerBridgeRoute
  ApiPublicTwilioSmsRoute: typeof ApiPublicTwilioSmsRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
  ApiPublicTwilioVoiceFallbackRoute: typeof ApiPublicTwilioVoiceFallbackRoute
  ApiPublicVoiceToolsBookAppointmentRoute: typeof ApiPublicVoiceToolsBookAppointmentRoute
  ApiPublicVoiceToolsFindSlotsRoute: typeof ApiPublicVoiceToolsFindSlotsRoute
  ApiPublicVoicemailAudioRoute: typeof ApiPublicVoicemailAudioRoute
  ApiPublicWidgetChatRoute: typeof ApiPublicWidgetChatRoute
  ApiPublicWidgetEmbedDotjsRoute: typeof ApiPublicWidgetEmbedDotjsRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicWidgetConfigAgentIdRoute: typeof ApiPublicWidgetConfigAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/widget/$agentId': {
      id: '/widget/$agentId'
      path: '/widget/$agentId'
      fullPath: '/widget/$agentId'
      preLoaderRoute: typeof WidgetAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/phone-numbers': {
      id: '/dashboard/phone-numbers'
      path: '/phone-numbers'
      fullPath: '/dashboard/phone-numbers'
      preLoaderRoute: typeof DashboardPhoneNumbersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge': {
      id: '/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat-widget': {
      id: '/dashboard/chat-widget'
      path: '/chat-widget'
      fullPath: '/dashboard/chat-widget'
      preLoaderRoute: typeof DashboardChatWidgetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agent': {
      id: '/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof DashboardAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations/': {
      id: '/dashboard/conversations/'
      path: '/'
      fullPath: '/dashboard/conversations/'
      preLoaderRoute: typeof DashboardConversationsIndexRouteImport
      parentRoute: typeof DashboardConversationsRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/conversations/blocked': {
      id: '/dashboard/conversations/blocked'
      path: '/blocked'
      fullPath: '/dashboard/conversations/blocked'
      preLoaderRoute: typeof DashboardConversationsBlockedRouteImport
      parentRoute: typeof DashboardConversationsRoute
    }
    '/dashboard/conversations/$conversationId': {
      id: '/dashboard/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/dashboard/conversations/$conversationId'
      preLoaderRoute: typeof DashboardConversationsConversationIdRouteImport
      parentRoute: typeof DashboardConversationsRoute
    }
    '/dashboard/agents/$agentId': {
      id: '/dashboard/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/dashboard/agents/$agentId'
      preLoaderRoute: typeof DashboardAgentsAgentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/tickets': {
      id: '/dashboard/admin/tickets'
      path: '/tickets'
      fullPath: '/dashboard/admin/tickets'
      preLoaderRoute: typeof DashboardAdminTicketsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/health': {
      id: '/dashboard/admin/health'
      path: '/health'
      fullPath: '/dashboard/admin/health'
      preLoaderRoute: typeof DashboardAdminHealthRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/api/public/owner-chat': {
      id: '/api/public/owner-chat'
      path: '/api/public/owner-chat'
      fullPath: '/api/public/owner-chat'
      preLoaderRoute: typeof ApiPublicOwnerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/users/': {
      id: '/dashboard/admin/users/'
      path: '/'
      fullPath: '/dashboard/admin/users/'
      preLoaderRoute: typeof DashboardAdminUsersIndexRouteImport
      parentRoute: typeof DashboardAdminUsersRoute
    }
    '/dashboard/admin/tickets/': {
      id: '/dashboard/admin/tickets/'
      path: '/'
      fullPath: '/dashboard/admin/tickets/'
      preLoaderRoute: typeof DashboardAdminTicketsIndexRouteImport
      parentRoute: typeof DashboardAdminTicketsRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/users/$userId': {
      id: '/dashboard/admin/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/admin/users/$userId'
      preLoaderRoute: typeof DashboardAdminUsersUserIdRouteImport
      parentRoute: typeof DashboardAdminUsersRoute
    }
    '/dashboard/admin/tickets/$ticketId': {
      id: '/dashboard/admin/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/dashboard/admin/tickets/$ticketId'
      preLoaderRoute: typeof DashboardAdminTicketsTicketIdRouteImport
      parentRoute: typeof DashboardAdminTicketsRoute
    }
    '/api/public/widget/embed.js': {
      id: '/api/public/widget/embed.js'
      path: '/api/public/widget/embed.js'
      fullPath: '/api/public/widget/embed.js'
      preLoaderRoute: typeof ApiPublicWidgetEmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/chat': {
      id: '/api/public/widget/chat'
      path: '/api/public/widget/chat'
      fullPath: '/api/public/widget/chat'
      preLoaderRoute: typeof ApiPublicWidgetChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voicemail/audio': {
      id: '/api/public/voicemail/audio'
      path: '/api/public/voicemail/audio'
      fullPath: '/api/public/voicemail/audio'
      preLoaderRoute: typeof ApiPublicVoicemailAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-tools/find-slots': {
      id: '/api/public/voice-tools/find-slots'
      path: '/api/public/voice-tools/find-slots'
      fullPath: '/api/public/voice-tools/find-slots'
      preLoaderRoute: typeof ApiPublicVoiceToolsFindSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-tools/book-appointment': {
      id: '/api/public/voice-tools/book-appointment'
      path: '/api/public/voice-tools/book-appointment'
      fullPath: '/api/public/voice-tools/book-appointment'
      preLoaderRoute: typeof ApiPublicVoiceToolsBookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice-fallback': {
      id: '/api/public/twilio/voice-fallback'
      path: '/api/public/twilio/voice-fallback'
      fullPath: '/api/public/twilio/voice-fallback'
      preLoaderRoute: typeof ApiPublicTwilioVoiceFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms': {
      id: '/api/public/twilio/sms'
      path: '/api/public/twilio/sms'
      fullPath: '/api/public/twilio/sms'
      preLoaderRoute: typeof ApiPublicTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/dialer-bridge': {
      id: '/api/public/twilio/dialer-bridge'
      path: '/api/public/twilio/dialer-bridge'
      fullPath: '/api/public/twilio/dialer-bridge'
      preLoaderRoute: typeof ApiPublicTwilioDialerBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/callback': {
      id: '/api/public/twilio/callback'
      path: '/api/public/twilio/callback'
      fullPath: '/api/public/twilio/callback'
      preLoaderRoute: typeof ApiPublicTwilioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outlook-calendar/callback': {
      id: '/api/public/outlook-calendar/callback'
      path: '/api/public/outlook-calendar/callback'
      fullPath: '/api/public/outlook-calendar/callback'
      preLoaderRoute: typeof ApiPublicOutlookCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-delete-threads': {
      id: '/api/public/hooks/auto-delete-threads'
      path: '/api/public/hooks/auto-delete-threads'
      fullPath: '/api/public/hooks/auto-delete-threads'
      preLoaderRoute: typeof ApiPublicHooksAutoDeleteThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/callback': {
      id: '/api/public/google-calendar/callback'
      path: '/api/public/google-calendar/callback'
      fullPath: '/api/public/google-calendar/callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs/postcall': {
      id: '/api/public/elevenlabs/postcall'
      path: '/api/public/elevenlabs/postcall'
      fullPath: '/api/public/elevenlabs/postcall'
      preLoaderRoute: typeof ApiPublicElevenlabsPostcallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/config/$agentId': {
      id: '/api/public/widget/config/$agentId'
      path: '/api/public/widget/config/$agentId'
      fullPath: '/api/public/widget/config/$agentId'
      preLoaderRoute: typeof ApiPublicWidgetConfigAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminTicketsRouteChildren {
  DashboardAdminTicketsTicketIdRoute: typeof DashboardAdminTicketsTicketIdRoute
  DashboardAdminTicketsIndexRoute: typeof DashboardAdminTicketsIndexRoute
}

const DashboardAdminTicketsRouteChildren: DashboardAdminTicketsRouteChildren = {
  DashboardAdminTicketsTicketIdRoute: DashboardAdminTicketsTicketIdRoute,
  DashboardAdminTicketsIndexRoute: DashboardAdminTicketsIndexRoute,
}

const DashboardAdminTicketsRouteWithChildren =
  DashboardAdminTicketsRoute._addFileChildren(
    DashboardAdminTicketsRouteChildren,
  )

interface DashboardAdminUsersRouteChildren {
  DashboardAdminUsersUserIdRoute: typeof DashboardAdminUsersUserIdRoute
  DashboardAdminUsersIndexRoute: typeof DashboardAdminUsersIndexRoute
}

const DashboardAdminUsersRouteChildren: DashboardAdminUsersRouteChildren = {
  DashboardAdminUsersUserIdRoute: DashboardAdminUsersUserIdRoute,
  DashboardAdminUsersIndexRoute: DashboardAdminUsersIndexRoute,
}

const DashboardAdminUsersRouteWithChildren =
  DashboardAdminUsersRoute._addFileChildren(DashboardAdminUsersRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminHealthRoute: typeof DashboardAdminHealthRoute
  DashboardAdminTicketsRoute: typeof DashboardAdminTicketsRouteWithChildren
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRouteWithChildren
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminHealthRoute: DashboardAdminHealthRoute,
  DashboardAdminTicketsRoute: DashboardAdminTicketsRouteWithChildren,
  DashboardAdminUsersRoute: DashboardAdminUsersRouteWithChildren,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardConversationsRouteChildren {
  DashboardConversationsConversationIdRoute: typeof DashboardConversationsConversationIdRoute
  DashboardConversationsBlockedRoute: typeof DashboardConversationsBlockedRoute
  DashboardConversationsIndexRoute: typeof DashboardConversationsIndexRoute
}

const DashboardConversationsRouteChildren: DashboardConversationsRouteChildren =
  {
    DashboardConversationsConversationIdRoute:
      DashboardConversationsConversationIdRoute,
    DashboardConversationsBlockedRoute: DashboardConversationsBlockedRoute,
    DashboardConversationsIndexRoute: DashboardConversationsIndexRoute,
  }

const DashboardConversationsRouteWithChildren =
  DashboardConversationsRoute._addFileChildren(
    DashboardConversationsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardAgentRoute: typeof DashboardAgentRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardChatWidgetRoute: typeof DashboardChatWidgetRoute
  DashboardConversationsRoute: typeof DashboardConversationsRouteWithChildren
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardKnowledgeRoute: typeof DashboardKnowledgeRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardPhoneNumbersRoute: typeof DashboardPhoneNumbersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAgentsAgentIdRoute: typeof DashboardAgentsAgentIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardAgentRoute: DashboardAgentRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardChatWidgetRoute: DashboardChatWidgetRoute,
  DashboardConversationsRoute: DashboardConversationsRouteWithChildren,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardKnowledgeRoute: DashboardKnowledgeRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardPhoneNumbersRoute: DashboardPhoneNumbersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAgentsAgentIdRoute: DashboardAgentsAgentIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WidgetAgentIdRoute: WidgetAgentIdRoute,
  ApiPublicOwnerChatRoute: ApiPublicOwnerChatRoute,
  ApiPublicElevenlabsPostcallRoute: ApiPublicElevenlabsPostcallRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
  ApiPublicHooksAutoDeleteThreadsRoute: ApiPublicHooksAutoDeleteThreadsRoute,
  ApiPublicOutlookCalendarCallbackRoute: ApiPublicOutlookCalendarCallbackRoute,
  ApiPublicTwilioCallbackRoute: ApiPublicTwilioCallbackRoute,
  ApiPublicTwilioDialerBridgeRoute: ApiPublicTwilioDialerBridgeRoute,
  ApiPublicTwilioSmsRoute: ApiPublicTwilioSmsRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
  ApiPublicTwilioVoiceFallbackRoute: ApiPublicTwilioVoiceFallbackRoute,
  ApiPublicVoiceToolsBookAppointmentRoute:
    ApiPublicVoiceToolsBookAppointmentRoute,
  ApiPublicVoiceToolsFindSlotsRoute: ApiPublicVoiceToolsFindSlotsRoute,
  ApiPublicVoicemailAudioRoute: ApiPublicVoicemailAudioRoute,
  ApiPublicWidgetChatRoute: ApiPublicWidgetChatRoute,
  ApiPublicWidgetEmbedDotjsRoute: ApiPublicWidgetEmbedDotjsRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicWidgetConfigAgentIdRoute: ApiPublicWidgetConfigAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
